name: e2e

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  e2e:
    name: windows-latest
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Install TFLint
      run: |
        curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_windows_amd64.zip")" -o tflint.zip
        unzip tflint.zip -d /bin
        rm tflint.zip
        tflint -v
      shell: bash
    - name: Install plugin
      run: |
        mkdir -p ~/.tflint.d/plugins
        go build -o ~/.tflint.d/plugins/tflint-ruleset-azurerm.exe
      shell: bash
    - name: Run E2E tests
      run: make e2e
